DROP TABLE IF EXISTS Owner;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS color;
DROP TABLE IF EXISTS model;

CREATE TABLE Owner (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  gender TEXT NOT NULL,
  birth TIMESTAMP,
  password TEXT NOT NULL
);

CREATE TABLE car (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  color_id INTEGER NOT NULL,
  model_id INTEGER NOT NULL,
  owner_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  FOREIGXN KEY (owner_id) REFERENCES Owner (id)
  FOREIGXN KEY (color_id) REFERENCES color (id)
  FOREIGXN KEY (model_id) REFERENCES model (id)
);

CREATE TABLE color (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
);

CREATE TABLE model (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
);